### ISSUE TITLE
CI: CMake fails to install on macOS

### ISSUE THREAD

**Issue by certik** [fortran-lang/stdlib#122]
An example error: https://github.com/fortran-lang/stdlib/pull/119/checks?check_run_id=406043264
```
2020-01-23T21:35:25.6403130Z [36;1mpip install --upgrade cmake[0m
2020-01-23T21:35:25.6548030Z shell: /bin/bash -e {0}
2020-01-23T21:35:25.6548180Z env:
2020-01-23T21:35:25.6548280Z   CI: ON
2020-01-23T21:35:25.6548350Z   CMAKE_BUILD_PARALLEL_LEVEL: 2
2020-01-23T21:35:25.6548470Z   CTEST_OUTPUT_ON_FAILURE: ON
2020-01-23T21:35:25.6548570Z   CTEST_PARALLEL_LEVEL: 2
2020-01-23T21:35:25.6548670Z   CTEST_TIME_TIMEOUT: 5
2020-01-23T21:35:25.6548730Z   HOMEBREW_NO_ANALYTICS: ON
2020-01-23T21:35:25.6548830Z   HOMEBREW_NO_AUTO_UPDATE: ON
2020-01-23T21:35:25.6548920Z   HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: ON
2020-01-23T21:35:25.6549010Z   HOMEBREW_NO_GITHUB_API: ON
2020-01-23T21:35:25.6549080Z   HOMEBREW_NO_INSTALL_CLEANUP: ON
2020-01-23T21:35:25.6549180Z   FC: gfortran-7
2020-01-23T21:35:25.6549270Z   GCC_V: 7
2020-01-23T21:35:25.6549370Z   pythonLocation: /Users/runner/hostedtoolcache/Python/3.8.1/x64
2020-01-23T21:35:25.6549440Z ##[endgroup]
2020-01-23T21:35:26.9423920Z Collecting cmake
2020-01-23T21:35:26.9650240Z   Downloading cmake-3.13.2.post1.tar.gz (27 kB)
2020-01-23T21:35:27.4408240Z     ERROR: Command errored out with exit status 1:
2020-01-23T21:35:27.4409820Z      command: /Users/runner/hostedtoolcache/Python/3.8.1/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-fbiqmw5w/cmake/setup.py'"'"'; __file__='"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-fbiqmw5w/cmake/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-fbiqmw5w/cmake/pip-egg-info
2020-01-23T21:35:27.4411610Z          cwd: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-fbiqmw5w/cmake/
2020-01-23T21:35:27.4421200Z     Complete output (5 lines):
2020-01-23T21:35:27.4422140Z     Traceback (most recent call last):
2020-01-23T21:35:27.4424820Z       File "<string>", line 1, in <module>
2020-01-23T21:35:27.4426060Z       File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-fbiqmw5w/cmake/setup.py", line 7, in <module>
2020-01-23T21:35:27.4426520Z         from skbuild import setup
2020-01-23T21:35:27.4427270Z     ModuleNotFoundError: No module named 'skbuild'
2020-01-23T21:35:27.4427760Z     ----------------------------------------
2020-01-23T21:35:27.4450470Z ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by zbeekman** [comment]
Feel free to tag me with issues like this in the future. Your solution looks good to me, so I think there's nothing else to do.

Work is super busy right now so I haven't been able to keep as close tabs on this repo as I would like.
